# Generated by Django 5.1.7 on 2025-04-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materias',
            new_name='Materia',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='materias',
            new_name='materia',
        ),
    ]
