# Generated by Django 5.1.7 on 2025-04-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_entry_comentario_alter_comentario_options'),
    ]

    operations = [
    ]
